FROM python:3.12

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt
RUN pip install pytest pytest-django

# Copy the Django project
COPY . /app/

# Copy the pytest configuration file
COPY pytest.ini /app/

# Run tests
CMD ["pytest"]
